name: Feature Request
description: Suggest a new feature or enhancement for RLAF
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe what you'd like to see.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Critic Perspective
        - New Algorithm Implementation
        - Integration (Hugging Face, W&B, etc.)
        - Performance Optimization
        - Documentation
        - Example/Tutorial
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How would you use this feature? Provide a code example if applicable.
      placeholder: |
        ```python
        # Example usage
        ```
      render: python

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: This would help users who...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Links to papers, other implementations, etc...
